#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PalmSens.Core.Simplified.Android.Resource", IsApplication=false)]

namespace PalmSens.Core.Simplified.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public static int autoScaleTextStyleView = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int minTextSize = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public static int background_grey = 2131034115;
			
			// aapt resource value: 0x7f050004
			public static int background_lightgrey = 2131034116;
			
			// aapt resource value: 0x7f050005
			public static int background_lightgrey_down = 2131034117;
			
			// aapt resource value: 0x7f050001
			public static int black = 2131034113;
			
			// aapt resource value: 0x7f050002
			public static int palmsensblue = 2131034114;
			
			// aapt resource value: 0x7f050000
			public static int white = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int ic_menu_connect = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int ic_menu_connected = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int pstouch_button = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int pstouch_button_container = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public static int button_scan = 2131296260;
			
			// aapt resource value: 0x7f090003
			public static int new_devices = 2131296259;
			
			// aapt resource value: 0x7f090001
			public static int paired_devices = 2131296257;
			
			// aapt resource value: 0x7f090005
			public static int scan = 2131296261;
			
			// aapt resource value: 0x7f090002
			public static int title_new_devices = 2131296258;
			
			// aapt resource value: 0x7f090000
			public static int title_paired_devices = 2131296256;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int device_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int device_name = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public static int bluetooth_option_menu = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060010
			public static int ApplicationName = 2131099664;
			
			// aapt resource value: 0x7f06000f
			public static int Hello = 2131099663;
			
			// aapt resource value: 0x7f060002
			public static int bt_not_enabled_leaving = 2131099650;
			
			// aapt resource value: 0x7f06000c
			public static int button_scan = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public static int connect = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public static int discoverable = 2131099662;
			
			// aapt resource value: 0x7f060009
			public static int none_found = 2131099657;
			
			// aapt resource value: 0x7f060008
			public static int none_paired = 2131099656;
			
			// aapt resource value: 0x7f060001
			public static int not_connected = 2131099649;
			
			// aapt resource value: 0x7f060006
			public static int scanning = 2131099654;
			
			// aapt resource value: 0x7f060007
			public static int select_device = 2131099655;
			
			// aapt resource value: 0x7f060000
			public static int send = 2131099648;
			
			// aapt resource value: 0x7f060004
			public static int title_connected_to = 2131099652;
			
			// aapt resource value: 0x7f060003
			public static int title_connecting = 2131099651;
			
			// aapt resource value: 0x7f060005
			public static int title_not_connected = 2131099653;
			
			// aapt resource value: 0x7f06000b
			public static int title_other_devices = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public static int title_paired_devices = 2131099658;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070006
			public static int BlueToothTheme = 2131165190;
			
			// aapt resource value: 0x7f070004
			public static int BlueToothTheme_ButtonStyle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public static int BlueToothTheme_ListViewStyle = 2131165189;
			
			// aapt resource value: 0x7f070003
			public static int BlueToothTheme_TextStyle = 2131165187;
			
			// aapt resource value: 0x7f070002
			public static int BlueToothTheme_TitleTextStyle = 2131165186;
			
			// aapt resource value: 0x7f070000
			public static int BlueToothTheme_WindowTitleBackground = 2131165184;
			
			// aapt resource value: 0x7f070001
			public static int BlueToothTheme_WindowTitleStyle = 2131165185;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public static int device_filter = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AutoScaleTextView = new int[] {
					2130771969};
			
			// aapt resource value: 0
			public static int AutoScaleTextView_minTextSize = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
